#.
pipeline:
  test:
    image: majexa/ngn
    commands:
      - su user ci onlyUpdate
      - /etc/init.d/mysql start
      - su user pm localServer createDatabaseConfig
      - su user tst proj g test

